-- Me Fui de Argentina · Chat público v31
-- Ejecutar una vez en Supabase > SQL Editor > New query.
-- Este archivo también activa el contador real de interesados en planes.

create table if not exists public.plan_intereses (
  plan_id bigint not null references public.planes_sociales(id) on delete cascade,
  client_id uuid not null,
  created_at timestamptz not null default now(),
  primary key (plan_id, client_id)
);

alter table public.plan_intereses enable row level security;

create or replace function public.registrar_interes_plan(p_plan_id bigint, p_client_id uuid)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer;
  v_capacity integer;
  v_status text;
begin
  select interesados_count, cupo, estado
    into v_count, v_capacity, v_status
  from public.planes_sociales
  where id = p_plan_id
  for update;

  if not found or v_status <> 'aprobado' then
    raise exception 'PLAN_UNAVAILABLE';
  end if;

  if exists (
    select 1 from public.plan_intereses
    where plan_id = p_plan_id and client_id = p_client_id
  ) then
    return v_count;
  end if;

  if v_capacity is not null and v_count >= v_capacity then
    raise exception 'PLAN_FULL';
  end if;

  insert into public.plan_intereses (plan_id, client_id)
  values (p_plan_id, p_client_id);

  update public.planes_sociales
  set interesados_count = interesados_count + 1
  where id = p_plan_id
  returning interesados_count into v_count;

  return v_count;
end;
$$;

revoke all on function public.registrar_interes_plan(bigint, uuid) from public;
grant execute on function public.registrar_interes_plan(bigint, uuid) to anon, authenticated;

create table if not exists public.chat_mensajes (
  id bigint generated by default as identity primary key,
  ciudad text not null check (ciudad in (
    'Valencia', 'Madrid', 'Barcelona', 'Málaga', 'Alicante', 'Sevilla'
  )),
  apodo text not null check (char_length(apodo) between 2 and 30),
  mensaje text not null check (char_length(mensaje) between 2 and 280),
  plan_id bigint references public.planes_sociales(id) on delete set null,
  estado text not null default 'visible' check (estado in ('visible', 'oculto')),
  created_at timestamptz not null default now()
);

create index if not exists chat_mensajes_ciudad_fecha_idx
  on public.chat_mensajes (ciudad, created_at desc)
  where estado = 'visible';

alter table public.chat_mensajes enable row level security;

drop policy if exists "Mensajes visibles son publicos" on public.chat_mensajes;
create policy "Mensajes visibles son publicos"
  on public.chat_mensajes for select
  to anon, authenticated
  using (estado = 'visible' and created_at >= now() - interval '15 days');

drop policy if exists "Administradores leen todos los mensajes" on public.chat_mensajes;
create policy "Administradores leen todos los mensajes"
  on public.chat_mensajes for select
  to authenticated
  using (true);

drop policy if exists "Administradores moderan mensajes" on public.chat_mensajes;
create policy "Administradores moderan mensajes"
  on public.chat_mensajes for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Administradores eliminan mensajes" on public.chat_mensajes;
create policy "Administradores eliminan mensajes"
  on public.chat_mensajes for delete
  to authenticated
  using (true);

create table if not exists public.chat_rate_limits (
  client_id uuid primary key,
  last_sent_at timestamptz not null default '2000-01-01',
  window_started_at timestamptz not null default now(),
  messages_in_window integer not null default 0
);

alter table public.chat_rate_limits enable row level security;

create table if not exists public.chat_reportes (
  id bigint generated by default as identity primary key,
  mensaje_id bigint not null references public.chat_mensajes(id) on delete cascade,
  motivo text not null check (motivo in (
    'spam', 'acoso', 'estafa', 'datos-personales', 'otro'
  )),
  comentario text check (comentario is null or char_length(comentario) <= 300),
  estado text not null default 'pendiente' check (estado in ('pendiente', 'revisado')),
  created_at timestamptz not null default now()
);

create index if not exists chat_reportes_estado_fecha_idx
  on public.chat_reportes (estado, created_at desc);

alter table public.chat_reportes enable row level security;

drop policy if exists "Administradores leen reportes de chat" on public.chat_reportes;
create policy "Administradores leen reportes de chat"
  on public.chat_reportes for select
  to authenticated
  using (true);

drop policy if exists "Administradores revisan reportes de chat" on public.chat_reportes;
create policy "Administradores revisan reportes de chat"
  on public.chat_reportes for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Administradores eliminan reportes de chat" on public.chat_reportes;
create policy "Administradores eliminan reportes de chat"
  on public.chat_reportes for delete
  to authenticated
  using (true);

create or replace function public.publicar_mensaje_chat(
  p_client_id uuid,
  p_ciudad text,
  p_apodo text,
  p_mensaje text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_rate public.chat_rate_limits%rowtype;
  v_message_id bigint;
  v_nickname text := trim(p_apodo);
  v_message text := trim(p_mensaje);
begin
  if p_ciudad not in ('Valencia', 'Madrid', 'Barcelona', 'Málaga', 'Alicante', 'Sevilla') then
    raise exception 'INVALID_CITY';
  end if;
  if char_length(v_nickname) not between 2 and 30 then
    raise exception 'INVALID_NICKNAME';
  end if;
  if char_length(v_message) not between 2 and 280 then
    raise exception 'INVALID_MESSAGE';
  end if;
  if v_message ~* '(https?://|www\.|t\.me/|bit\.ly/|tinyurl\.)' then
    raise exception 'LINKS_NOT_ALLOWED';
  end if;

  insert into public.chat_rate_limits (client_id)
  values (p_client_id)
  on conflict (client_id) do nothing;

  select * into v_rate
  from public.chat_rate_limits
  where client_id = p_client_id
  for update;

  if v_rate.last_sent_at > now() - interval '7 seconds' then
    raise exception 'RATE_LIMIT';
  end if;

  if v_rate.window_started_at < now() - interval '1 hour' then
    v_rate.window_started_at := now();
    v_rate.messages_in_window := 0;
  end if;

  if v_rate.messages_in_window >= 30 then
    raise exception 'HOURLY_LIMIT';
  end if;

  if exists (
    select 1 from public.chat_mensajes
    where ciudad = p_ciudad
      and lower(apodo) = lower(v_nickname)
      and lower(mensaje) = lower(v_message)
      and created_at > now() - interval '2 minutes'
  ) then
    raise exception 'DUPLICATE_MESSAGE';
  end if;

  insert into public.chat_mensajes (ciudad, apodo, mensaje)
  values (p_ciudad, v_nickname, v_message)
  returning id into v_message_id;

  update public.chat_rate_limits
  set last_sent_at = now(),
      window_started_at = v_rate.window_started_at,
      messages_in_window = v_rate.messages_in_window + 1
  where client_id = p_client_id;

  delete from public.chat_mensajes
  where created_at < now() - interval '15 days';

  return v_message_id;
end;
$$;

revoke all on function public.publicar_mensaje_chat(uuid, text, text, text) from public;
grant execute on function public.publicar_mensaje_chat(uuid, text, text, text) to anon, authenticated;

create or replace function public.reportar_mensaje_chat(
  p_mensaje_id bigint,
  p_motivo text,
  p_comentario text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_report_id bigint;
begin
  if p_motivo not in ('spam', 'acoso', 'estafa', 'datos-personales', 'otro') then
    raise exception 'INVALID_REASON';
  end if;
  if p_comentario is not null and char_length(trim(p_comentario)) > 300 then
    raise exception 'COMMENT_TOO_LONG';
  end if;
  if not exists (
    select 1 from public.chat_mensajes
    where id = p_mensaje_id and estado = 'visible'
  ) then
    raise exception 'MESSAGE_NOT_FOUND';
  end if;

  insert into public.chat_reportes (mensaje_id, motivo, comentario)
  values (p_mensaje_id, p_motivo, nullif(trim(p_comentario), ''))
  returning id into v_report_id;

  return v_report_id;
end;
$$;

revoke all on function public.reportar_mensaje_chat(bigint, text, text) from public;
grant execute on function public.reportar_mensaje_chat(bigint, text, text) to anon, authenticated;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'chat_mensajes'
  ) then
    alter publication supabase_realtime add table public.chat_mensajes;
  end if;
end $$;

comment on table public.chat_mensajes is
  'Mensajes públicos temporales del chat social por ciudad.';
comment on table public.chat_reportes is
  'Reportes moderables de mensajes del chat comunitario.';
