-- Me Fui de Argentina · MVP Planes sociales
-- Ejecutar una vez en Supabase > SQL Editor > New query.

create table if not exists public.planes_sociales (
  id bigint generated by default as identity primary key,
  titulo text not null check (char_length(titulo) between 3 and 80),
  ciudad text not null check (char_length(ciudad) between 2 and 60),
  categoria text not null check (categoria in (
    'mateadas', 'after-office', 'deportes', 'salidas',
    'networking', 'nuevos', 'idiomas', 'otros'
  )),
  descripcion text not null check (char_length(descripcion) between 20 and 500),
  fecha_evento timestamptz not null,
  cupo integer check (cupo is null or cupo between 2 and 500),
  contacto text not null check (char_length(contacto) between 3 and 160),
  organizador text not null check (char_length(organizador) between 2 and 60),
  estado text not null default 'pendiente' check (estado in (
    'pendiente', 'aprobado', 'rechazado', 'finalizado'
  )),
  destacado boolean not null default false,
  interesados_count integer not null default 0 check (interesados_count >= 0),
  enlace_externo text,
  notas_admin text,
  created_at timestamptz not null default now()
);

create index if not exists planes_sociales_publicos_idx
  on public.planes_sociales (estado, destacado desc, fecha_evento asc);

alter table public.planes_sociales enable row level security;

drop policy if exists "Planes aprobados son publicos" on public.planes_sociales;
create policy "Planes aprobados son publicos"
  on public.planes_sociales for select
  to anon, authenticated
  using (estado = 'aprobado');

drop policy if exists "Cualquiera puede proponer un plan" on public.planes_sociales;
create policy "Cualquiera puede proponer un plan"
  on public.planes_sociales for insert
  to anon, authenticated
  with check (
    estado = 'pendiente'
    and destacado = false
    and interesados_count = 0
  );

drop policy if exists "Administradores leen todos los planes" on public.planes_sociales;
create policy "Administradores leen todos los planes"
  on public.planes_sociales for select
  to authenticated
  using (true);

drop policy if exists "Administradores actualizan planes" on public.planes_sociales;
create policy "Administradores actualizan planes"
  on public.planes_sociales for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Administradores eliminan planes" on public.planes_sociales;
create policy "Administradores eliminan planes"
  on public.planes_sociales for delete
  to authenticated
  using (true);

comment on table public.planes_sociales is
  'Propuestas sociales moderadas de Me Fui de Argentina.';
